export function userContactTemplate(name: string) {
  const container = "max-width:600px;margin:0 auto;background:#ffffff;border-radius:10px;overflow:hidden;font-family:Arial,Helvetica,sans-serif;";
  const header = "background:#0f172a;padding:30px 20px;text-align:center;color:white;";
  const section = "padding:30px;background:#ffffff;color:#1e293b;";
  const button = "display:inline-block;margin-top:20px;background:#0f172a;color:white;padding:12px 26px;font-size:15px;border-radius:6px;text-decoration:none;font-weight:500;";
  const logoStyle = "max-width:150px;height:auto;margin-bottom:12px;";

  return `
    <div style="${container}">
      <!-- Header with Logo -->
      <div style="${header}">
        <img src="https://alpine-prestige-rides.ch/_next/image?url=%2Flogo.png&w=256&q=75" alt="Alpine Prestige Rides" style="${logoStyle}" />
        <h2 style="margin:0;font-weight:600;font-size:22px;">Thank You for Contacting Alpine</h2>
        <p style="margin:6px 0 0;font-size:13px;opacity:0.85;">We’ve received your message</p>
      </div>

      <!-- Content Section -->
      <div style="${section}">
        <p style="font-size:15px;">Dear <strong>${name}</strong>,</p>

        <p style="font-size:15px;line-height:1.6;">
          Thank you for reaching out to Alpine. Your message has been successfully delivered to our support team.
        </p>

        <p style="font-size:15px;line-height:1.6;">
          We strive to respond as quickly as possible. One of our team members will get back to you shortly.
        </p>

        <a href="https://alpine-prestige-rides.ch" style="${button}">Visit Alpine Website</a>

        <div style="margin-top:26px;font-size:13px;color:#94a3b8;">
          <hr style="border:0;border-top:1px solid #e2e8f0;margin:22px 0;" />
          <p style="margin:0;">This message is automatically generated by Alpine Customer Support.</p>
        </div>
      </div>
    </div>
  `;
}
